### ISSUE TITLE
TTY error

### ISSUE THREAD

**Issue by wulms** [SichaoYang/W2MHS#1]
Hi SichaoYang,

do you know where the following error comes from?

> Segmenting hyperintensities on input images 
> Segmenting subject: w2mhs_0_30005_3dt1 using DNN Classification.
> the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
> Error using csvread (line 35)
> File not found.
> Error in WhyD_detect (line 45)
> oo = csvread(fullfile(training_path, 'DNN_testing_file.csv'));
> Error in WhyD_setup (line 135)
>     names_stack{n,1} = WhyD_detect(names_stack{n,1}, training_path);
> Error in WhyD_GUI>run_button_Callback (line 231)
>     WhyD_setup(output_name, output_path, input_images, output_ids, ...
> Error in gui_mainfcn (line 95)
>         feval(varargin{:});
> Error in WhyD_GUI (line 27)
>         gui_mainfcn(gui_State, varargin{:});
> Error in
> matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)WhyD_GUI('run_button_Callback',hObject,eventdata,guidata(hObject)) 
> Error while evaluating UIControl Callback.
>

Okay, on Ubuntu 18.04 your script seems working until now. So I think it has something to do with a docker call inside on of your functions, where you had the prefix "winpty"

**Comment by SichaoYang** [comment]
Sorry wulms, there are so many problems with the previous MATLAB + dockerized python solution, so I reorganized the code, removed all MATLAB-python interfaces, and rewrote the GUI.
